const data = {
  products: [
    {
      name: 'Free Shirt',
      catagory: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 453,
      discount: 'ETB7,632.84',
      discountType: 'Choice Day',
      description: 'A popular shirt for new comers',
      alt: 'A popular shirt',
    },
    {
      name: 'Short Shirt',
      catagory: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 123,
      discount: 'ETB8,271.34',
      discountType: 'Choice Day',
      description: 'nice brand popular shirt for everyone ',
      alt: 'A popular shirt',
    },
    {
      name: 'L Shirt',
      catagory: 'Shirt',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 430,
      discount: 'ETB5,453.34',
      description: 'brand new comming t shirt for us',
      alt: 'A popular shirt',
    },
    {
      name: 'Fat Shirt',
      catagory: 'Shirt',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 200,
      discount: 'ETB3,759.28',
      description: 'pants for boys quality added',
      alt: 'A popular fatty shirt',
    },
    {
      name: 'Fat Shirt',
      catagory: 'Shirt',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 55,
      discount: 'ETB1,257.44',
      discountType: 'Choice Day',
      description: 'likely and lovely pant form differnet purpose',
      alt: 'A popular pant',
    },
    {
      name: 'Fat Shirt',
      catagory: 'Shirt',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 150,
      discount: 'ETB9,753.83',
      description: 'pants for long living',
      alt: 'A popular pant',
    },
    {
      name: 'Fat Shirt',
      catagory: 'Shirt',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numOfSold: 100,
      discount: 'ETB2,453.34',
      discountType: 'Choice Day',
      description: 'pant for our gentlemen and fashinists',
      alt: 'A popular pant',
    },
  ],
};

export default data;
